apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ApostolosGerodimos/argo-apps.git
    targetRevision: main
    path: my-nginx
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: playground
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
