apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.21.0
    helm:
      values: |
        alertmanager:
          enabled: false

        pushgateway:
          enabled: false

        server:
          persistentVolume:
            enabled: false
          extraArgs:
            enable-feature: remote-write-receiver
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        service:
          type: ClusterIP

        serverFiles:
          prometheus.yml:
            scrape_configs:
              - job_name: 'kubernetes-nodes'
                static_configs:
                  - targets: ['localhost:9100']

              - job_name: 'kubernetes-pods'
                kubernetes_sd_configs:
                  - role: pod

              - job_name: 'nginx-metrics'
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_label_app]
                    action: keep
                    regex: my-nginx-nginx
                  - source_labels: [__meta_kubernetes_pod_container_port_number]
                    action: keep
                    regex: "9113"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
